"""Add CineBot models and user fields

Revision ID: 3d2666391f12
Revises: a24832406f92
Create Date: 2025-08-31 01:36:51.487147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2666391f12'
down_revision = 'a24832406f92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_column('square_card_id')

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('square_customer_id')
        batch_op.drop_column('square_subscription_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_cinebot_consent')
        batch_op.drop_index('idx_users_content_filter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_content_filter', ['content_filter_level'], unique=False)
        batch_op.create_index('idx_users_cinebot_consent', ['cinebot_consent_given'], unique=False)

    with op.batch_alter_table('user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('square_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('square_card_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
